---
- name: Docker server installation with ymal script
  hosts: all
  become: true
  tasks:
    - name: Old packages remove from server.
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-client
        - docker-client-latest
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine

    - name: install yum utils
      yum: 
        name: yum-utils
        state: latest
    - name: Add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-edge'
        option: enabled
    - name: Required Package installation
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - epel-release
        - wget
        - python3-pip
        - device-mapper-persistent-data
        - lvm2
        - python-docker-py
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: Adding user to docker
      user:
        name: mayank
        groups: docker
        append: yes
      become: yes
    - name: Install python dependency for docker
      command: "pip3 install docker-py" 
      notify:
        - docker start

  handlers: 
    - name: docker start
      ansible.builtin.service:
        name: docker
        state: restarted

