---
- name: Create a container
  hosts: all
  tasks: 
    - name: web container
      docker_container:
        name: web
        image: web-server
        state: started
        ports: 
        - "8080:80"
        tty: true
        detach: true
